"""empty message

Revision ID: 375ff3f54c82
Revises: ef466a4e800c
Create Date: 2022-05-11 14:04:59.679221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '375ff3f54c82'
down_revision = 'ef466a4e800c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'comments')
    op.drop_column('comments', 'category')
    op.add_column('pitches', sa.Column('comment_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'pitches', 'comments', ['comment_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pitches', type_='foreignkey')
    op.drop_column('pitches', 'comment_id')
    op.add_column('comments', sa.Column('category', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.add_column('comments', sa.Column('comments', sa.VARCHAR(length=300), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
