"""name changed to username.

Revision ID: 638e15369c38
Revises: 38b425dc3d75
Create Date: 2022-05-09 10:10:48.010398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '638e15369c38'
down_revision = '38b425dc3d75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('user_id', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
