"""adds addition colums to user and creates the comments table 

Revision ID: 79b62cf5be75
Revises: 884dff7718c4
Create Date: 2022-05-08 17:04:24.443936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79b62cf5be75'
down_revision = '884dff7718c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('bio', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('profile_pic_path', sa.String(), nullable=True))
    op.drop_column('user', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('user', 'profile_pic_path')
    op.drop_column('user', 'bio')
    # ### end Alembic commands ###
