"""adds the comments class

Revision ID: eaa7d80ce167
Revises: 638e15369c38
Create Date: 2022-05-09 17:49:46.545347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eaa7d80ce167'
down_revision = '638e15369c38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('category', sa.String(length=120), nullable=False))
    op.add_column('comments', sa.Column('body', sa.String(length=120), nullable=False))
    op.add_column('comments', sa.Column('comments', sa.String(length=300), nullable=False))
    op.add_column('comments', sa.Column('upvotes', sa.Integer(), nullable=False))
    op.add_column('comments', sa.Column('downvotes', sa.Integer(), nullable=False))
    op.alter_column('user', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('comments', 'downvotes')
    op.drop_column('comments', 'upvotes')
    op.drop_column('comments', 'comments')
    op.drop_column('comments', 'body')
    op.drop_column('comments', 'category')
    # ### end Alembic commands ###
